#import = ["~/.alacritty-colorscheme/themes/{scheme_name}.toml"]
#theme = "Belge"

[colors]
#author = "kareem"
#name = "Belge"

[colors.bright]
black = "#454545"
blue = "#87ceeb"
cyan = "#87ceeb"
green = "#b6e354"
magenta = "#996600"
red = "#fc7ca5"
white = "#fdfdfd"
yellow = "#fd971f"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "#252525"
blue = "#6495ed"
cyan = "#b0c4de"
green = "#a6e22e"
magenta = "#deb887"
red = "#ef6769"
white = "#dbdcdc"
yellow = "#fd971f"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[cursor.style]
#blink_interval = 75
blinking = "Always"
#shape = "Block"

[font]
size = 12

[font.glyph_offset]
x = 0
y = 0

[font.normal]
#bold = "Font family"
family = "DejaVu Sans Mono"
style = "regular"

[font.offset]
x = 0
y = 0

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
opacity = 0.85

[window.padding]
x = 10
y = 10
